//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExclusionEngine.Web
{
    public partial class CsvImport
    {
        protected global::System.Web.UI.WebControls.Label MessageLabel;
        protected global::System.Web.UI.WebControls.DropDownList ClientDropDown;
        protected global::System.Web.UI.WebControls.FileUpload CsvFileUpload;
        protected global::System.Web.UI.WebControls.Button ImportButton;
        protected global::System.Web.UI.WebControls.Panel ResultsPanel;
        protected global::System.Web.UI.WebControls.Label SummaryLabel;
        protected global::System.Web.UI.WebControls.GridView ResultsGrid;
    }
}
